source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.3.1'
inhibit_all_warnings!

target 'AKUSexagenaryCycle' do
  pod "AKUSexagenaryCycle", :path => "../", :inhibit_warnings => false

  pod 'Kiwi'
  pod 'AZDateBuilder'
  pod 'NSDate-Escort'
end
